import type { Metadata } from "next";
import "./globals.css";
import { PropsWithChildren } from "react";
import { Analytics } from "@vercel/analytics/react";

export const metadata: Metadata = {
  title: "GFGKIIT",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: PropsWithChildren) {
  return (
    <html lang="en" className="block h-full w-full">
      <body className="block h-full w-full bg-[url(/bg.webp)] bg-repeat text-zinc-200 overflow-x-hidden">
        {children}
        <Analytics />
      </body>
    </html>
  );
}
